### ISSUE TITLE
[Jobs] Quartz - Failed to obtain DB connection from data source 'DefaultDB'

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#1010]
After some period of time (~24h) the following issue appears in the Cloud Foundry Docker distribution, that's causing Dirigible stop working:
```java
[ERROR] [DirigibleClusteredScheduler_Worker-6] org.quartz.core.ErrorLogger - An error occurred while org.quartz.impl.jdbcjobstore.JobStoreSupport$46@60f54501
org.quartz.JobPersistenceException: Failed to obtain DB connection from data source 'DefaultDB': org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: Stream Closed"; "/workspace/target/dirigible/h2/SystemDB.h2.db"; SQL statement:
COMMIT [90031-176]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:783) ~[quartz-2.3.2.jar:na]
	at org.eclipse.dirigible.core.scheduler.quartz.CustomJobStore.getConnection(CustomJobStore.java:96) ~[dirigible-core-scheduler-5.12.9.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3854) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retryExecuteInNonManagedTXLock(JobStoreSupport.java:3819) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.triggeredJobComplete(JobStoreSupport.java:3116) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.QuartzScheduler.notifyJobStoreJobComplete(QuartzScheduler.java:1786) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:269) ~[quartz-2.3.2.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: Stream Closed"; "/workspace/target/dirigible/h2/SystemDB.h2.db"; SQL statement:
COMMIT [90031-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:167) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.convertIOException(DbException.java:329) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.store.FileStore.write(FileStore.java:332) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.store.PageStore.writePage(PageStore.java:1369) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.store.PageStreamData.write(PageStreamData.java:107) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.store.PageOutputStream.storePage(PageOutputStream.java:148) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.store.PageOutputStream.write(PageOutputStream.java:131) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.store.PageLog.write(PageLog.java:551) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.store.PageLog.commit(PageLog.java:571) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.store.PageStore.commit(PageStore.java:1477) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Database.commit(Database.java:1926) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Session.commit(Session.java:494) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:47) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.CommandContainer.update(CommandContainer.java:79) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Command.executeUpdate(Command.java:254) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.commit(JdbcConnection.java:467) ~[h2-1.3.176.jar:1.3.176]
	at org.apache.commons.dbcp2.DelegatingConnection.commit(DelegatingConnection.java:367) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at org.apache.commons.dbcp2.DelegatingConnection.commit(DelegatingConnection.java:367) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at org.eclipse.dirigible.database.api.wrappers.WrappedConnection.close(WrappedConnection.java:107) ~[dirigible-database-api-5.12.9.jar:na]
	at org.eclipse.dirigible.database.api.wrappers.WrappedDataSource.forceRelaseConnection(WrappedDataSource.java:179) ~[dirigible-database-api-5.12.9.jar:na]
	at org.eclipse.dirigible.database.api.wrappers.WrappedDataSource.checkConnections(WrappedDataSource.java:163) ~[dirigible-database-api-5.12.9.jar:na]
	at org.eclipse.dirigible.database.api.wrappers.WrappedDataSource.getConnection(WrappedDataSource.java:115) ~[dirigible-database-api-5.12.9.jar:na]
	at org.eclipse.dirigible.core.scheduler.quartz.DatasourceConnectionProvider.getConnection(DatasourceConnectionProvider.java:32) ~[dirigible-core-scheduler-5.12.9.jar:na]
	at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:780) ~[quartz-2.3.2.jar:na]
	... 8 common frames omitted
Caused by: java.io.IOException: Stream Closed
	at java.base/java.io.RandomAccessFile.writeBytes(Native Method) ~[na:na]
	at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:559) ~[na:na]
	at org.h2.store.fs.FileDisk.write(FilePathDisk.java:468) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.store.fs.FileUtils.writeFully(FileUtils.java:361) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.store.FileStore.write(FileStore.java:329) ~[h2-1.3.176.jar:1.3.176]
	... 30 common frames omitted
```

**Comment by ThuF** [comment]
Could be related to the allocated storage, the instance was created with the following command:
```
cf push dirigible \
--docker-image=dirigiblelabs/dirigible-sap-cf:latest \
--hostname dirigible-<org-name> \
-m 2G -k 2G
```
