### ISSUE TITLE
[Core] Unable to create publish request, due to long User ID

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#1041]
Long User IDs (emails) cause issue when creating a publish request:
```java
Caused by: org.h2.jdbc.JdbcSQLDataException: Value too long for column "PUBREQ_CREATED_BY VARCHAR(32)": "'xxx@yyy.zzz' (36)"; SQL statement:
INSERT INTO DIRIGIBLE_PUBLISH_REQUESTS (PUBREQ_ID, PUBREQ_WORKSPACE, PUBREQ_PATH, PUBREQ_REGISTRY, PUBREQ_CREATED_BY, PUBREQ_CREATED_AT, PUBREQ_COMMAND) VALUES (?, ?, ?, ?, ?, ?, ?) [22001-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.value.TypeInfo.getValueTooLongException(TypeInfo.java:535) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.value.TypeInfo.cast(TypeInfo.java:520) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:378) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.dml.Insert.insertRows(Insert.java:187) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.dml.Insert.update(Insert.java:151) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.CommandContainer.update(CommandContainer.java:198) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Command.executeUpdate(Command.java:251) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152) ~[h2-1.4.200.jar:1.4.200]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at org.eclipse.dirigible.database.persistence.processors.entity.PersistenceInsertProcessor.insert(PersistenceInsertProcessor.java:102) ~[dirigible-database-persistence-6.0.0-SNAPSHOT.jar:na]
	... 64 common frames omitted
```

Solution -> Increase the column size.

**Comment by ThuF** [comment]
Affected columns to be updated from `32` length to `128` length:
- [PublishLogDefinition.java#L42-L43](https://github.com/eclipse/dirigible/blob/master/modules/core/core-publisher/src/main/java/org/eclipse/dirigible/core/publisher/definition/PublishLogDefinition.java#L42-L43)
- [ODataContainerDefinition.java#L33-L34](https://github.com/eclipse/dirigible/blob/master/modules/odata/odata-api/src/main/java/org/eclipse/dirigible/engine/odata2/definition/ODataContainerDefinition.java#L33-L34)
- [ODataSchemaDefinition.java#L33-L34](https://github.com/eclipse/dirigible/blob/master/modules/odata/odata-api/src/main/java/org/eclipse/dirigible/engine/odata2/definition/ODataSchemaDefinition.java#L33-L34)
- [PublishRequestDefinition.java#L50-L51](https://github.com/eclipse/dirigible/blob/master/modules/core/core-publisher/src/main/java/org/eclipse/dirigible/core/publisher/definition/PublishRequestDefinition.java#L50-L51)
- [ODataMappingDefinition.java#L33-L34](https://github.com/eclipse/dirigible/blob/master/modules/odata/odata-api/src/main/java/org/eclipse/dirigible/engine/odata2/definition/ODataMappingDefinition.java#L33-L34)
- [BpmDefinition.java#L32-L33](https://github.com/eclipse/dirigible/blob/master/modules/bpm/bpm-flowable/src/main/java/org/eclipse/dirigible/bpm/flowable/definition/BpmDefinition.java#L32-L33)
- [RoleDefinition.java#L36-L37](https://github.com/eclipse/dirigible/blob/master/modules/core/core-security/src/main/java/org/eclipse/dirigible/core/security/definition/RoleDefinition.java#L36-L37)
- [ExtensionPointDefinition.java#L38-L39](https://github.com/eclipse/dirigible/blob/master/modules/core/core-extensions/src/main/java/org/eclipse/dirigible/core/extensions/definition/ExtensionPointDefinition.java#L38-L39)
- [ODataDefinition.java#L40-L41](https://github.com/eclipse/dirigible/blob/master/modules/odata/odata-api/src/main/java/org/eclipse/dirigible/engine/odata2/definition/ODataDefinition.java#L40-L41)
- [DataStructureModel.java#L44-L45](https://github.com/eclipse/dirigible/blob/master/modules/database/database-data-models/src/main/java/org/eclipse/dirigible/database/ds/model/DataStructureModel.java#L44-L45)
- [WebsocketDefinition.java#L44-L45](https://github.com/eclipse/dirigible/blob/master/modules/core/core-websockets/src/main/java/org/eclipse/dirigible/core/websockets/definition/WebsocketDefinition.java#L44-L45)
- [ExtensionDefinition.java#L41-L42](https://github.com/eclipse/dirigible/blob/master/modules/core/core-extensions/src/main/java/org/eclipse/dirigible/core/extensions/definition/ExtensionDefinition.java#L41-L42)
- [ListenerDefinition.java#L44-L45](https://github.com/eclipse/dirigible/blob/3b63f0bb2fe4f3df07987c9ab6048b55a8dfcebe/modules/core/core-messaging/src/main/java/org/eclipse/dirigible/core/messaging/definition/ListenerDefinition.java#L44-L45)
