### ISSUE TITLE
[Releng] SAP CMS - Startup Errors

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#1051]
Exceptions:

```java
Cannot create resource  object instance due to exception in the object factory javax.naming.NamingException: Cannot create resource  object instance due to exception in the object factory
	at com.sap.core.services.accessor.tomcat.support.DelegatingObjectFactory.getObjectInstanceFromFactory(DelegatingObjectFactory.java:109)
	at com.sap.core.services.accessor.tomcat.support.DelegatingObjectFactory.getObjectInstance(DelegatingObjectFactory.java:47)
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:96)
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:331)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:847)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:157)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:834)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:157)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:834)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:157)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:834)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:171)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:161)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at org.eclipse.dirigible.database.managed.ManagedDatabase.lookupDataSource(ManagedDatabase.java:106)
	at org.eclipse.dirigible.database.managed.ManagedDatabase.initialize(ManagedDatabase.java:71)
	at org.eclipse.dirigible.database.managed.ManagedDatabase.<init>(ManagedDatabase.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:456)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.eclipse.dirigible.database.api.DatabaseModule.configure(DatabaseModule.java:61)
	at org.eclipse.dirigible.commons.api.module.DirigibleModulesInstallerModule.configure(DirigibleModulesInstallerModule.java:72)
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initializeModules(DirigibleInitializer.java:79)
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initialize(DirigibleInitializer.java:56)
	at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:39)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4763)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5232)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:836)
Caused by: javax.naming.NamingException: No persistence configuration available for resource name [jdbc/DefaultDB], check datasource bindings for this application
	at com.sap.cloud.runtime.kotyo.persistence.client.PersistenceDataSourceFactory.getObjectInstance(PersistenceDataSourceFactory.java:51)
	at com.sap.core.services.accessor.tomcat.support.DelegatingObjectFactory.getObjectInstanceFromFactory(DelegatingObjectFactory.java:99)
	... 42 common frames omitted
```
```java
Error while trying to invoke the method org.eclipse.dirigible.repository.api.IRepository.getLastModified() of a null object returned from org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.getRepository() java.lang.NullPointerException: while trying to invoke the method org.eclipse.dirigible.repository.api.IRepository.getLastModified() of a null object returned from org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.getRepository()
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.beforeSynchronizing(AbstractSynchronizer.java:48)
	at org.eclipse.dirigible.core.security.synchronizer.SecuritySynchronizer.synchronize(SecuritySynchronizer.java:79)
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizerJob$1.run(AbstractSynchronizerJob.java:52)
	at org.eclipse.dirigible.commons.timeout.TimeLimited$1.call(TimeLimited.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:836)
```

**Comment by ThuF** [comment]
Additional exception observed:

```java
Failed installing Dirigible Module [Local Repository Module]. java.lang.UnsupportedClassVersionError: com/github/benmanes/caffeine/cache/Caffeine has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [com.github.benmanes.caffeine.cache.Caffeine])
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2490)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:876)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1379)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1223)
	at org.eclipse.dirigible.repository.api.RepositoryCache.initialize(RepositoryCache.java:34)
	at org.eclipse.dirigible.repository.api.RepositoryCache.<init>(RepositoryCache.java:25)
	at org.eclipse.dirigible.repository.local.LocalRepositoryDao.<init>(LocalRepositoryDao.java:55)
	at org.eclipse.dirigible.repository.fs.FileSystemRepository.createRepository(FileSystemRepository.java:143)
	at org.eclipse.dirigible.repository.fs.FileSystemRepository.<init>(FileSystemRepository.java:117)
	at org.eclipse.dirigible.repository.local.LocalRepository.<init>(LocalRepository.java:74)
	at org.eclipse.dirigible.repository.local.module.LocalRepositoryModule.createInstance(LocalRepositoryModule.java:67)
	at org.eclipse.dirigible.repository.local.module.LocalRepositoryModule.configure(LocalRepositoryModule.java:46)
	at org.eclipse.dirigible.commons.api.module.DirigibleModulesInstallerModule.configure(DirigibleModulesInstallerModule.java:72)
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initializeModules(DirigibleInitializer.java:79)
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initialize(DirigibleInitializer.java:56)
	at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:39)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4763)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5232)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:836)
```
