### ISSUE TITLE
[core/v3/java] Cannot make subsequent Java method invocations with the same ref. object

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#114]
Windows 10
Tomcat 8.5.23
Dirigible 3
Rhino JS runtime

Try this: 
var java = require('core/v3/java');
java.call('org.eclipse.dirigible.api.v3.core.ContextFacade', 'set', ['a', '1']);
var value = java.call('org.eclipse.dirigible.api.v3.core.ContextFacade', 'get', ['a']);

Error stack trace:
2017-10-23 14:25:23.641 [ERROR] [http-nio-8080-exec-8] o.e.d.e.j.r.p.RhinoJavascriptEngineExecutor - **TypeError: Cannot call property call in object [JavaPackage java]. It is not a function, it is "object".** (prj1/svc/a.js#10)
2017-10-23 14:25:23.652 [ERROR] [http-nio-8080-exec-8] o.e.d.e.j.s.JavascriptEngineRestService - org.mozilla.javascript.EcmaError: TypeError: Cannot call property call in object [JavaPackage java]. It is not a function, it is "object". (prj1/svc/a.js#10)
org.eclipse.dirigible.commons.api.scripting.ScriptingException: org.mozilla.javascript.EcmaError: TypeError: Cannot call property call in object [JavaPackage java]. It is not a function, it is "object". (prj1/svc/a.js#10)
	at org.eclipse.dirigible.engine.js.rhino.processor.RhinoJavascriptEngineExecutor.executeService(RhinoJavascriptEngineExecutor.java:92) ~[dirigible-engine-js-rhino-3.0.jar:na]
...
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot call property call in object [JavaPackage java]. It is not a function, it is "object". (prj1/svc/a.js#10)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951) ~[rhino-1.7.7.1.jar:1.7.7.1]
...
org.eclipse.dirigible.engine.js.rhino.processor.RhinoJavascriptEngineExecutor.executeService(RhinoJavascriptEngineExecutor.java:82) ~[dirigible-engine-js-rhino-3.0.jar:na]
	... 63 common frames omitted

Works with v8. Seems to be a problem with Rhino interpreting the java. notation.

**Comment by delchev** [comment]
Yes, indeed it seems a Rhino issue, but you can use the different name of the variable e.g. _java:

```
var _java = require('core/v3/java');
_java.call('org.eclipse.dirigible.api.v3.core.ContextFacade', 'set', ['a', '1']);
var value = _java.call('org.eclipse.dirigible.api.v3.core.ContextFacade', 'get', ['a']);
```
