### ISSUE TITLE
[Tests] Workspace is created in the users directory

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#1757]
Exception:

```java
[main] INFO org.eclipse.dirigible.core.workspace.service.WorkspacesCoreService - Workspace created [/users/guest/TestWorkspace1]
[main] ERROR org.eclipse.dirigible.core.workspace.service.Workspace - /Users/<username>
org.apache.commons.io.IOExceptionList: /Users/<username>
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:331)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
	at org.eclipse.dirigible.core.workspace.service.Workspace.deleteProject(Workspace.java:88)
	at org.eclipse.dirigible.core.workspace.service.test.WorkspaceTest.deleteProjectTest(WorkspaceTest.java:132)
```

> _**Important**: It seems that files under `/Users/<username>/` are being deleted e.g. `/Users/<username>/Desktop/` `/Users/<username>/Downloads/`, etc._

Related changes:
- https://github.com/eclipse/dirigible/issues/1756
- https://github.com/eclipse/dirigible/commit/bed7bc5e52d67169da545e7037dfb34af5ad5683

**Comment by ThuF** [comment]
Fixed with:
- https://github.com/eclipse/dirigible/commit/d1460b07293fec8ccda66d0684d4bece331f6032
