### ISSUE TITLE
[Git] Error occurred while pushing project

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#181]
Stack trace:

```java
2017-12-13 14:58:25,471 ERROR [http-nio-8080-exec-9] o.e.d.c.g.c.PushCommand [PushCommand.java:182] Error occurred while pushing project [http].
java.io.IOException: Error in creating directories for the file: /Users/Temp/Data/Work/Tools/SDK/Apache Tomcat - 8.5.5/temp/dirigible_git_api-v3-http8060383636642074288253456664092079
                at org.eclipse.dirigible.core.git.utils.GitFileUtils.copyProjectToDirectory(GitFileUtils.java:318) ~[dirigible-core-git-3.1.0-SNAPSHOT.jar:na]
                at org.eclipse.dirigible.core.git.command.PushCommand.pushProjectToGitRepository(PushCommand.java:150) [dirigible-core-git-3.1.0-SNAPSHOT.jar:na]
                at org.eclipse.dirigible.core.git.command.PushCommand.execute(PushCommand.java:84) [dirigible-core-git-3.1.0-SNAPSHOT.jar:na]
                at org.eclipse.dirigible.runtime.git.processor.GitProcessor.push(GitProcessor.java:100) [dirigible-runtime-ide-git-3.1.0-SNAPSHOT.jar:na]
                at org.eclipse.dirigible.runtime.git.service.GitRestService.pushProject(GitRestService.java:180) [dirigible-runtime-ide-git-3.1.0-SNAPSHOT.jar:na]
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
                at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
                at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180) [cxf-core-3.1.11.jar:3.1.11]
                at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.1.11.jar:3.1.11]
                at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189) [cxf-rt-frontend-jaxrs-3.1.11.jar:3.1.11]
                at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99) [cxf-rt-frontend-jaxrs-3.1.11.jar:3.1.11]
                at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.1.11.jar:3.1.11]
                at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.1.11.jar:3.1.11]
                at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.1.11.jar:3.1.11]
                at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.1.11.jar:3.1.11]
                at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:262) [cxf-rt-transports-http-3.1.11.jar:3.1.11]
                at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.1.11.jar:3.1.11]
                at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.1.11.jar:3.1.11]
                at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.1.11.jar:3.1.11]
                at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180) [cxf-rt-transports-http-3.1.11.jar:3.1.11]
                at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:299) [cxf-rt-transports-http-3.1.11.jar:3.1.11]
                at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:218) [cxf-rt-transports-http-3.1.11.jar:3.1.11]
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [servlet-api.jar:na]
                at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:274) [cxf-rt-transports-http-3.1.11.jar:3.1.11]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [catalina.jar:8.5.5]
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.5]
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.5]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.5]
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.5]
                at org.eclipse.dirigible.runtime.core.filter.HttpContextFilter.doFilter(HttpContextFilter.java:56) [dirigible-runtime-core-3.1.0-SNAPSHOT.jar:na]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.5]
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.5]
                at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:474) [jetty-servlets-9.4.5.v20170502.jar:9.4.5.v20170502]
                at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:319) [jetty-servlets-9.4.5.v20170502.jar:9.4.5.v20170502]
                at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:289) [jetty-servlets-9.4.5.v20170502.jar:9.4.5.v20170502]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.5]
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.5]
                at org.eclipse.jetty.servlets.QoSFilter.doFilter(QoSFilter.java:201) [jetty-servlets-9.4.5.v20170502.jar:9.4.5.v20170502]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.5]
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.5]
                at com.google.inject.servlet.DefaultFilterPipeline.dispatch(DefaultFilterPipeline.java:43) [guice-servlet-3.0.jar:na]
                at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.5]
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.5]
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.5]
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [catalina.jar:8.5.5]
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:586) [catalina.jar:8.5.5]
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.5]
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.5.5]
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) [catalina.jar:8.5.5]
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.5]
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [catalina.jar:8.5.5]
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) [tomcat-coyote.jar:8.5.5]
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.5]
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) [tomcat-coyote.jar:8.5.5]
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) [tomcat-coyote.jar:8.5.5]
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.5]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.5]
                at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```

**Comment by delchev** [comment]
Fixed with:
https://github.com/eclipse/dirigible/commit/b194bfb48cdda51cbb540b4b8cbbb4052967e8d8
