### ISSUE TITLE
Class not found MessagingSynchronizerJob

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#187]
```java
2018-01-08 12:51:56,142 ERROR [QuartzScheduler_DirigibleClusteredScheduler-MisfireHandler] o.q.i.j.JobStoreTX [JobStoreSupport.java:4002] MisfireHandler: Error handling misfires: Couldn't store trigger 'dirigible-internal.dirigible-internal-messaging-synchronizer-job' for 'dirigible-internal.dirigible-internal-messaging-synchronizer-job' job:Couldn't retrieve job because a required class was not found: org.eclipse.dirigible.core.messaging.synchronizer.MessagingSynchronizerJob
org.quartz.JobPersistenceException: Couldn't store trigger 'dirigible-internal.dirigible-internal-messaging-synchronizer-job' for 'dirigible-internal.dirigible-internal-messaging-synchronizer-job' job:Couldn't retrieve job because a required class was not found: org.eclipse.dirigible.core.messaging.synchronizer.MessagingSynchronizerJob
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1228) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1042) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:991) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3249) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3997) [quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4018) [quartz-2.3.0.jar:na]
Caused by: org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: org.eclipse.dirigible.core.messaging.synchronizer.MessagingSynchronizerJob
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1393) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1210) ~[quartz-2.3.0.jar:na]
	... 5 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.eclipse.dirigible.core.messaging.synchronizer.MessagingSynchronizerJob
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285) ~[catalina.jar:8.5.5]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119) ~[catalina.jar:8.5.5]
	at org.quartz.simpl.InitThreadContextClassLoadHelper.loadClass(InitThreadContextClassLoadHelper.java:72) ~[quartz-2.3.0.jar:na]
	at org.quartz.simpl.CascadingClassLoadHelper.loadClass(CascadingClassLoadHelper.java:114) ~[quartz-2.3.0.jar:na]
	at org.quartz.simpl.CascadingClassLoadHelper.loadClass(CascadingClassLoadHelper.java:138) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:852) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1390) ~[quartz-2.3.0.jar:na]
	... 6 common frames omitted
```

**Comment by ThuF** [comment]
Fixed after hard-reset (deleting derby db & repository content). The issue was due to class refactoring.
