### ISSUE TITLE
[Core] Synchronizers - CSVIM not working on PostgreSQL

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#1930]
It seems that the `CsvimSynchronizer` is not working as expected on PostgreSQL database.

**Exception:**
```java
o.e.d.c.c.s.CsvimSynchronizer - An error occurred while trying to execute the data import: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 69
org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 69
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgCallableStatement.executeWithFlags(PgCallableStatement.java:78) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117) ~[postgresql-42.1.4.jar:42.1.4]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-java7-2.4.13.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyCallableStatement.executeQuery(HikariProxyCallableStatement.java) ~[HikariCP-java7-2.4.13.jar:na]
	at org.eclipse.dirigible.cms.csvim.service.CsvimProcessor.recordExists(CsvimProcessor.java:153) ~[dirigible-cms-csvim-6.3.9.jar:na]
	at org.eclipse.dirigible.cms.csvim.service.CsvimProcessor.process(CsvimProcessor.java:129) ~[dirigible-cms-csvim-6.3.9.jar:na]
	at org.eclipse.dirigible.cms.csvim.synchronizer.CsvimSynchronizer.executeCsvim(CsvimSynchronizer.java:371) ~[dirigible-cms-csvim-6.3.9.jar:na]
	at org.eclipse.dirigible.cms.csvim.synchronizer.CsvimSynchronizer.processCsvimArtefacts(CsvimSynchronizer.java:339) ~[dirigible-cms-csvim-6.3.9.jar:na]
	at org.eclipse.dirigible.cms.csvim.synchronizer.CsvimSynchronizer.synchronize(CsvimSynchronizer.java:110) ~[dirigible-cms-csvim-6.3.9.jar:na]
	at org.eclipse.dirigible.core.scheduler.synchronizer.OrderedSynchronizer.synchronize(OrderedSynchronizer.java:74) ~[dirigible-core-scheduler-6.3.9.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizerJob$1.run(AbstractSynchronizerJob.java:46) ~[dirigible-core-scheduler-6.3.9.jar:na]
	at org.eclipse.dirigible.commons.timeout.TimeLimited$1.call(TimeLimited.java:38) ~[dirigible-commons-timeout-6.3.9.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by ThuF** [comment]
It seems this is the query that's being executed to check if the record exists:

```sql
SELECT DISTINCT 1 "GENE_ID" FROM "GENETYLLIS_GENE" WHERE ("GENE_ID" = ?)
```

- https://github.com/eclipse/dirigible/blob/e1baf1f8bc2014ef4ff2672f55d5a102dc325fcd/modules/cms/cms-csvim/src/main/java/org/eclipse/dirigible/cms/csvim/service/CsvimProcessor.java#L144-L157

**Comment by ThuF** [comment]
Fixed with:
- https://github.com/eclipse/dirigible/commit/e3ae01e7d26a19176898faf14b718a138d7e3dac
- https://github.com/eclipse/dirigible/commit/ac8992020bb80121ff2275fde4bb8fa202768ccf
