### ISSUE TITLE
Server shuts down on wrong project.json

### ISSUE THREAD

**Issue by BorisNen** [eclipse/dirigible#2006]
We have the following project structure:

- project
  - modules
    - pages
      - Home-page
        - project.json
      - project.json 
  - releng

The guid of pages/project.json is project-pages.
The guid of pages/Home-page/project.json is Home-page

Steps to reproduce:
1. Create the same project structure
2. Add the second (wrong) project.json that is under Home-page/
3. Build project
4. Copy war into tomcat and run it
5. If you try to access the IDE under localhost:8080/ it gives out 404

The error from the log is

```
19-Aug-2022 12:39:03.117 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener]
	java.lang.RuntimeException: The name of the project folder must the same as the guid property in the project.json - [project-pages] and [Home-page]
		at org.eclipse.dirigible.engine.web.service.WebCoreService.setName(WebCoreService.java:289)
		at org.eclipse.dirigible.engine.web.service.WebCoreService.parseWeb(WebCoreService.java:254)
		at org.eclipse.dirigible.engine.web.synchronizer.WebSynchronizer.registerPredeliveredWeb(WebSynchronizer.java:131)
		at org.eclipse.dirigible.engine.web.synchronizer.WebClasspathContentHandler.isValid(WebClasspathContentHandler.java:46)
		at org.eclipse.dirigible.commons.api.content.AbstractClasspathContentHandler.accept(AbstractClasspathContentHandler.java:68)
		at org.eclipse.dirigible.commons.api.content.ClasspathContentLoader.load(ClasspathContentLoader.java:66)
		at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.loadPredeliveredContent(DirigibleInitializer.java:133)
		at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initialize(DirigibleInitializer.java:67)
		at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:47)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:938)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1784)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by delchev** [comment]
It should be fixed as a proper handling at development time. Wrong content at runtime should stop the server until the content is fixed properly during development.
