### ISSUE TITLE
[Generation] Generation from a EDM model does not work

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#2756]
**Description**
Generation from a EDM model does not work with the latest version from master

**To Reproduce**
1. Create a EDM model
2. Try to generate

**Expected behavior**

**Exception**
o.e.d.c.e.j.s.JavascriptHandler - TypeError: "params" is not a writable property of [Module]
org.graalvm.polyglot.PolyglotException: TypeError: "params" is not a writable property of [Module]
	at <js>.execute(./rs/resource-http-controller:82) ~[na:na]
	at <js>.execute(./resource-method:13) ~[na:na]
	at <js>.:module:eval(generate.mjs:28) ~[na:na]
	at org.graalvm.polyglot.Context.eval(Context.java:403) ~[graal-sdk-23.0.1.jar!/:na]
	at org.eclipse.dirigible.graalium.core.javascript.GraalJSCodeRunner.run(GraalJSCodeRunner.java:176) ~[dirigible-engine-graalium-execution-9.0.0-SNAPSHOT.jar!/:na]

org.graalvm.polyglot.PolyglotException: TypeError: "params" is not a writable property of [Module]] with root cause
org.graalvm.polyglot.PolyglotException: TypeError: "params" is not a writable property of [Module]
	at <js>.execute(./rs/resource-http-controller:82) ~[na:na]
	at <js>.execute(./resource-method:13) ~[na:na]
	at <js>.:module:eval(generate.mjs:28) ~[na:na]
	at org.graalvm.polyglot.Context.eval(Context.java:403) ~[graal-sdk-23.0.1.jar!/:na]
	at org.eclipse.dirigible.graalium.core.javascript.GraalJSCodeRunner.run(GraalJSCodeRunner.java:176) ~[dirigible-engine-graalium-execution-9.0.0-SNAPSHOT.jar!/:na]

**Comment by delchev** [comment]
LKG 8.11.4
