### ISSUE TITLE
[Database] PostgreSQL - Could not create ACTIVEMQ_MSGS table

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#316]
Exception:
```java
2018-08-16 08:09:22.916 [INFO ] [localhost-startStop-1] o.a.activemq.broker.BrokerService - Using Persistence Adapter: JDBCPersistenceAdapter(org.apache.commons.dbcp2.BasicDataSource@75b8b284)
2018-08-16 08:09:22.923 [INFO ] [localhost-startStop-1] o.a.a.s.jdbc.JDBCPersistenceAdapter - Database adapter driver override not found for : [postgresql_jdbc_driver].  Will use default implementation.
2018-08-16 08:09:22.941 [WARN ] [localhost-startStop-1] o.a.a.s.j.adapter.DefaultJDBCAdapter - Could not create JDBC tables; they could already exist. Failure was: CREATE TABLE ACTIVEMQ_MSGS(ID BIGINT NOT NULL, CONTAINER VARCHAR(250), MSGID_PROD VARCHAR(250), MSGID_SEQ BIGINT, EXPIRATION BIGINT, MSG BLOB, PRIMARY KEY ( ID ) ) Message: ERROR: type "blob" does not exist
  Position: 138 SQLState: 42704 Vendor code: 0
2018-08-16 08:09:22.951 [WARN ] [localhost-startStop-1] o.a.a.s.jdbc.JDBCPersistenceAdapter - Failure details: ERROR: type "blob" does not exist
  Position: 138
org.postgresql.util.PSQLException: ERROR: type "blob" does not exist
  Position: 138
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260) ~[postgresql-42.1.4.jar:42.1.4]
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at org.apache.activemq.store.jdbc.adapter.DefaultJDBCAdapter.executeStatement(DefaultJDBCAdapter.java:114) [activemq-jdbc-store-5.14.5.jar:5.14.5]
	at org.apache.activemq.store.jdbc.adapter.DefaultJDBCAdapter.doCreateTables(DefaultJDBCAdapter.java:92) [activemq-jdbc-store-5.14.5.jar:5.14.5]
	at org.apache.activemq.store.jdbc.JDBCPersistenceAdapter.init(JDBCPersistenceAdapter.java:304) [activemq-jdbc-store-5.14.5.jar:5.14.5]
	at org.apache.activemq.broker.LockableServiceSupport.preStart(LockableServiceSupport.java:89) [activemq-broker-5.14.5.jar:5.14.5]
	at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:54) [activemq-client-5.14.5.jar:5.14.5]
	at org.apache.activemq.broker.BrokerService.doStartPersistenceAdapter(BrokerService.java:675) [activemq-broker-5.14.5.jar:5.14.5]
	at org.apache.activemq.broker.BrokerService.startPersistenceAdapter(BrokerService.java:659) [activemq-broker-5.14.5.jar:5.14.5]
	at org.apache.activemq.broker.BrokerService.start(BrokerService.java:623) [activemq-broker-5.14.5.jar:5.14.5]
	at org.eclipse.dirigible.core.messaging.service.SchedulerManager.initialize(SchedulerManager.java:77) [dirigible-core-messaging-3.2.3-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.startupMessaging(DirigibleInitializer.java:202) [dirigible-service-core-3.2.3-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initialize(DirigibleInitializer.java:80) [dirigible-service-core-3.2.3-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:50) [dirigible-service-core-3.2.3-SNAPSHOT.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727) [catalina.jar:8.5.8]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189) [catalina.jar:8.5.8]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.5.8]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752) [catalina.jar:8.5.8]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728) [catalina.jar:8.5.8]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) [catalina.jar:8.5.8]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952) [catalina.jar:8.5.8]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823) [catalina.jar:8.5.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

**Comment by g051051** [comment]
Per [this issue](https://issues.apache.org/jira/browse/AMQ-6780), it's resolved with ActiveMQ 5.15.7 or higher (current version in Dirigible is 5.14.5).  I don't know how to test this, though.

**Comment by ThuF** [comment]
The error is expected to be logged in the console (from where Dirigible was started). As far as I remember, if that issue occurs then Dirigible won't initialize successfully and you can't access it. That's why we've set the `DIRIGIBLE_MESSAGING_USE_DEFAULT_DATABASE` environment variable to `false` _(as a workaround)_, while running against PostgreSQL.

In order to have setup against PostgreSQL the following environment variables should be set:
```
export DIRIGIBLE_DATABASE_PROVIDER=custom
export DIRIGIBLE_DATABASE_CUSTOM_DATASOURCES=POSTGRE
export DIRIGIBLE_DATABASE_DATASOURCE_NAME_DEFAULT=POSTGRE
export POSTGRE_URL=<postgre-jdbc-url> (e.g. jdbc:postgresql://localhost:5432/dirigible)
export POSTGRE_DRIVER=org.postgresql.Driver
export POSTGRE_USERNAME=<postgre-username> (e.g. postgres)
export POSTGRE_PASSWORD=<postgre-password (e.g. Abcd1234)
export DIRIGIBLE_SCHEDULER_DATABASE_DRIVER=org.postgresql.Driver
export DIRIGIBLE_SCHEDULER_DATABASE_URL=<postgre-jdbc-url> (e.g. jdbc:postgresql://localhost:5432/dirigible)
export DIRIGIBLE_SCHEDULER_DATABASE_USER=<postgre-username> (e.g. postgres)
export DIRIGIBLE_SCHEDULER_DATABASE_PASSWORD=<postgre-password (e.g. Abcd1234)
export DIRIGIBLE_MESSAGING_USE_DEFAULT_DATABASE=false
export DIRIGIBLE_FLOWABLE_USE_DEFAULT_DATABASE=false
```

In order to reproduce the issue, set the `DIRIGIBLE_MESSAGING_USE_DEFAULT_DATABASE` = `true`.

If you are using some of the local distributions of Drigible _(e.g. **server-all**)_, then the PostgreSQL JDBC driver should be placed in the `<Catalina-Home>/lib` directory.

If Docker _(e.g. **dirigiblelabs/dirigible-all**)_ is being used, there we've got the PostgreSQL JDBC driver pre-packaged. The driver that we are using in the Docker distributions is [postgresql-42.1.4](https://repo1.maven.org/maven2/org/postgresql/postgresql/42.1.4/postgresql-42.1.4.jar). In the help page, you can find a section how to [run Dirigible from a Docker image](https://www.dirigible.io/help/setup_docker.html).
```
docker run --name dirigible --rm \
-e DIRIGIBLE_DATABASE_PROVIDER=custom \
-e DIRIGIBLE_DATABASE_CUSTOM_DATASOURCES=POSTGRE \
-e DIRIGIBLE_DATABASE_DATASOURCE_NAME_DEFAULT=POSTGRE \
-e POSTGRE_URL=<postgre-jdbc-url> (e.g. jdbc:postgresql://localhost:5432/dirigible) \
-e POSTGRE_DRIVER=org.postgresql.Driver \
-e POSTGRE_USERNAME=<postgre-username> (e.g. postgres) \
-e POSTGRE_PASSWORD=<postgre-password (e.g. Abcd1234) \
-e DIRIGIBLE_SCHEDULER_DATABASE_DRIVER=org.postgresql.Driver \
-e DIRIGIBLE_SCHEDULER_DATABASE_URL=<postgre-jdbc-url> (e.g. jdbc:postgresql://localhost:5432/dirigible) \
-e DIRIGIBLE_SCHEDULER_DATABASE_USER=<postgre-username> (e.g. postgres) \
-e DIRIGIBLE_SCHEDULER_DATABASE_PASSWORD=<postgre-password (e.g. Abcd1234) \
-e DIRIGIBLE_MESSAGING_USE_DEFAULT_DATABASE=false \
-e DIRIGIBLE_FLOWABLE_USE_DEFAULT_DATABASE=false \
-p 8000:8000 -p 8080:8080 -p 8081:8081 \
dirigiblelabs/dirigible-all:latest

```
The complete list of environment variables can be found here: https://www.dirigible.io/help/setup_environment_variables.html

I've been using [PgAdmin](https://www.pgadmin.org/download/) to setup and run PostgreSQL locally.

**Comment by delchev** [comment]
```
export DIRIGIBLE_MESSAGING_USE_DEFAULT_DATABASE=true
export DIRIGIBLE_FLOWABLE_USE_DEFAULT_DATABASE=true
export DIRIGIBLE_DATABASE_NAMES_CASE_SENSITIVE=true
```

**Comment by delchev** [comment]
@g051051, can you please prepare a PR with the changed version for ActiveMQ (activemq.version) in the parent POM to 5.16.0.
From what I've just tested it fixes this particular issue, thanks for the suggested solution!

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/pull/666
