### ISSUE TITLE
[Database] PostgreSQL - Syntax error at or near "PRIMARY"

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#317]
Exception:
```java
2018-08-16 08:09:23.014 [WARN ] [localhost-startStop-1] o.a.a.s.j.adapter.DefaultJDBCAdapter - Could not create JDBC tables; they could already exist. Failure was: ALTER TABLE ACTIVEMQ_ACKS DROP PRIMARY KEY Message: ERROR: syntax error at or near "PRIMARY"
  Position: 32 SQLState: 42601 Vendor code: 0
2018-08-16 08:09:23.019 [WARN ] [localhost-startStop-1] o.a.a.s.jdbc.JDBCPersistenceAdapter - Failure details: ERROR: syntax error at or near "PRIMARY"
  Position: 32
org.postgresql.util.PSQLException: ERROR: syntax error at or near "PRIMARY"
  Position: 32
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260) ~[postgresql-42.1.4.jar:42.1.4]
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at org.apache.activemq.store.jdbc.adapter.DefaultJDBCAdapter.executeStatement(DefaultJDBCAdapter.java:114) [activemq-jdbc-store-5.14.5.jar:5.14.5]
	at org.apache.activemq.store.jdbc.adapter.DefaultJDBCAdapter.doCreateTables(DefaultJDBCAdapter.java:92) [activemq-jdbc-store-5.14.5.jar:5.14.5]
	at org.apache.activemq.store.jdbc.JDBCPersistenceAdapter.init(JDBCPersistenceAdapter.java:304) [activemq-jdbc-store-5.14.5.jar:5.14.5]
	at org.apache.activemq.broker.LockableServiceSupport.preStart(LockableServiceSupport.java:89) [activemq-broker-5.14.5.jar:5.14.5]
	at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:54) [activemq-client-5.14.5.jar:5.14.5]
	at org.apache.activemq.broker.BrokerService.doStartPersistenceAdapter(BrokerService.java:675) [activemq-broker-5.14.5.jar:5.14.5]
	at org.apache.activemq.broker.BrokerService.startPersistenceAdapter(BrokerService.java:659) [activemq-broker-5.14.5.jar:5.14.5]
	at org.apache.activemq.broker.BrokerService.start(BrokerService.java:623) [activemq-broker-5.14.5.jar:5.14.5]
	at org.eclipse.dirigible.core.messaging.service.SchedulerManager.initialize(SchedulerManager.java:77) [dirigible-core-messaging-3.2.3-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.startupMessaging(DirigibleInitializer.java:202) [dirigible-service-core-3.2.3-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initialize(DirigibleInitializer.java:80) [dirigible-service-core-3.2.3-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:50) [dirigible-service-core-3.2.3-SNAPSHOT.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727) [catalina.jar:8.5.8]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189) [catalina.jar:8.5.8]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.5.8]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752) [catalina.jar:8.5.8]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728) [catalina.jar:8.5.8]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) [catalina.jar:8.5.8]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952) [catalina.jar:8.5.8]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823) [catalina.jar:8.5.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

**Comment by delchev** [comment]
Fixed with the new version of ActiveMQ
