### ISSUE TITLE
[Templates] Listeners - Exception while processing message

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#3290]
![image](https://github.com/eclipse/dirigible/assets/4092083/5e8e5d3b-fd54-4d27-b4c5-578c2424caa6)

**Exception:**

```java
2024-01-24 10:21:56.837 [ERROR] [ActiveMQ Session Task-3] o.a.activemq.ActiveMQMessageConsumer - ID:dirigible-electra-5c66d56d56-pgqf4-39651-1706091182776-4:4:1:1 Exception while processing message: ID:dirigible-electra-5c66d56d56-pgqf4-39651-1706091182776-4:1:1:2:1
org.graalvm.polyglot.PolyglotException: SyntaxError: codbex-electra/gen/dao/SalesOrders/SalesOrderItem:1:38 Expected an operand but found import
(function(exports, module, require) { import { query } from "@dirigible/db";
                                      ^
codbex-electra/gen/dao/SalesOrders/SalesOrderItem:1:61 Expected ; but found @dirigible/db
(function(exports, module, require) { import { query } from "@dirigible/db";
                                                             ^
codbex-electra/gen/dao/SalesOrders/SalesOrderItem:2:0 Expected an operand but found import
import { producer } from "@dirigible/messaging";
^
codbex-electra/gen/dao/SalesOrders/SalesOrderItem:2:26 Expected ; but found @dirigible/messaging
import { producer } from "@dirigible/messaging";
                          ^
codbex-electra/gen/dao/SalesOrders/SalesOrderItem:3:0 Expected an operand but found import
import { extensions } from "@dirigible/extensions";
^
codbex-electra/gen/dao/SalesOrders/SalesOrderItem:3:28 Expected ; but found @dirigible/extensions
import { extensions } from "@dirigible/extensions";
                            ^
codbex-electra/gen/dao/SalesOrders/SalesOrderItem:4:0 Expected an operand but found import
import { dao as daoApi } from "@dirigible/db";
^
codbex-electra/gen/dao/SalesOrders/SalesOrderItem:4:31 Expected ; but found @dirigible/db
import { dao as daoApi } from "@dirigible/db";
                               ^
codbex-electra/gen/dao/SalesOrders/SalesOrderItem:59:0 Expected an operand but found export
export const list = (settings) => {
^
codbex-electra/gen/dao/SalesOrders/SalesOrderItem:63:0 Expected ) but found export
export const get = (id) => {
^
codbex-electra/gen/dao/SalesOrders/SalesOrderItem:64:1 Invalid return statement
	return dao.find(id);
	^
codbex-electra/gen/dao/SalesOrders/SalesOrderItem:65:0 Expected eof but found }
}
^

	at <js>.:module:eval(sales-order-handler.mjs:5) ~[na:na]
	at org.graalvm.polyglot.Context.eval(Context.java:402) ~[polyglot-23.1.1.jar!/:na]
	at org.eclipse.dirigible.graalium.core.javascript.GraalJSCodeRunner.run(GraalJSCodeRunner.java:149) ~[dirigible-engine-graalium-execution-10.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.graalium.core.DirigibleJavascriptCodeRunner.run(DirigibleJavascriptCodeRunner.java:160) ~[dirigible-engine-graalium-execution-core-10.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.graalium.core.DirigibleJavascriptCodeRunner.run(DirigibleJavascriptCodeRunner.java:174) ~[dirigible-engine-graalium-execution-core-10.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.graalium.core.DirigibleJavascriptCodeRunner.run(DirigibleJavascriptCodeRunner.java:165) ~[dirigible-engine-graalium-execution-core-10.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.components.listeners.service.AsynchronousMessageListener.executeOnMessageHandler(AsynchronousMessageListener.java:72) ~[dirigible-components-engine-listeners-10.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.components.listeners.service.AsynchronousMessageListener.onMessage(AsynchronousMessageListener.java:59) ~[dirigible-components-engine-listeners-10.0.0-SNAPSHOT.jar!/:na]
	at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1434) ~[activemq-client-6.0.1.jar!/:6.0.1]
	at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131) ~[activemq-client-6.0.1.jar!/:6.0.1]
	at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202) ~[activemq-client-6.0.1.jar!/:6.0.1]
	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) ~[activemq-client-6.0.1.jar!/:6.0.1]
	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) ~[activemq-client-6.0.1.jar!/:6.0.1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

Related project:
- https://github.com/codbex/codbex-electra/

**Comment by ThuF** [comment]
It seems that the issue is due to the migration of the generated DAOs from `CommonJS` to `ESM` introduced with:
-https://github.com/eclipse/dirigible/commit/1a2bfc0da20023cd00a3a98b31f0c3897c9cea76#diff-149b7c34765e105f34e4fd3c93ceb8368a65c51b60a879f645f77454f6d1debd

The `CommonJS` requires needs to be migrated to `ESM` imports:
- https://github.com/codbex/codbex-electra/blob/3e3a664276dbd90549acdaaa6e8633232c57b0e2/codbex-electra-opencart/synch/outbound/sales-order-handler.mjs#L5-L8

**Comment by ThuF** [comment]
The issue should be fixed with:
- https://github.com/codbex/codbex-electra/pull/76/files#diff-0fd5eb92130401ac62700ab6e7797cfe93886a257f1b09d7c15432b8dda72635

**Comment by ThuF** [comment]
Already fixed
