### ISSUE TITLE
Exception when publishing application from Snowpark

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [eclipse/dirigible#3559]
The following exception is thrown when trying to publish a generated full-stack application from deployed Dirigible on Snowpark
```
 [ERROR] [http-nio-80-exec-61] o.e.d.c.i.w.p.ProjectActionsPublisherHandler - Failed in executing the registry action: ProjectAction{name='Build TypeScript', commands=[CommandLine{os=UNIX, command='tsc'}, CommandLine{os=WINDOWS, command='cmd /c tsc'}], publish=false, registry=true} of project: addresses under workspace: workspace with: {}
java.lang.Exception: java.io.IOException: Cannot run program "tsc" (in directory "/target/dirigible/repository/root/registry/public/addresses"): error=2, No such file or directory
	at org.eclipse.dirigible.components.ide.workspace.service.ActionsService.executeCommandLine(ActionsService.java:204) ~[dirigible-components-ide-workspace-10.0.3.jar!/:na]
	at org.eclipse.dirigible.components.ide.workspace.project.ProjectActionsPublisherHandler.afterPublishProject(ProjectActionsPublisherHandler.java:144) ~[dirigible-components-ide-workspace-10.0.3.jar!/:na]
	at org.eclipse.dirigible.components.ide.workspace.project.ProjectActionsPublisherHandler.afterPublish(ProjectActionsPublisherHandler.java:121) ~[dirigible-components-ide-workspace-10.0.3.jar!/:na]
	at org.eclipse.dirigible.components.ide.workspace.service.PublisherService.publishResource(PublisherService.java:161) ~[dirigible-components-ide-workspace-10.0.3.jar!/:na]
	at org.eclipse.dirigible.components.ide.workspace.service.PublisherService.publish(PublisherService.java:100) ~[dirigible-components-ide-workspace-10.0.3.jar!/:na]
	at org.eclipse.dirigible.components.ide.workspace.service.PublisherService.publish(PublisherService.java:76) ~[dirigible-components-ide-workspace-10.0.3.jar!/:na]
	at org.eclipse.dirigible.components.ide.workspace.endpoint.PublisherEndpoint.publish(PublisherEndpoint.java:75) ~[dirigible-components-ide-workspace-10.0.3.jar!/:na]
```

**Comment by ThuF** [comment]
It seems that the Docker image doesn't have the `tsc` installed. Which Docker image is being used?
