### ISSUE TITLE
[Core] Unable to Access the Instance - Possible Leaking Database Connection

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#3665]
It seems that there are leaking database connections, as after leaving the Eclipse Dirigible up and running for a while (several hours) I get the following errors:

<img width="557" alt="Screenshot 2024-03-29 at 9 43 42" src="https://github.com/eclipse/dirigible/assets/4092083/56927ec9-c2d3-42b9-9cd8-62184378b71f">

```java
2024-03-29 09:41:59.350 [ERROR] [QuartzScheduler_EclipseDirigibleScheduler-Yordans-MacBook-Pro.local1711454649250_ClusterManager] [background] o.q.impl.jdbcjobstore.JobStoreTX - ClusterManager: Error managing cluster: Failed to obtain DB connection from data source 'SystemDB': java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30006ms.
org.quartz.JobPersistenceException: Failed to obtain DB connection from data source 'SystemDB': java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30006ms.
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:783) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3322) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972) ~[quartz-2.3.2.jar!/:na]
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30006ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[HikariCP-5.0.1.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181) ~[HikariCP-5.0.1.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[HikariCP-5.0.1.jar!/:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-5.0.1.jar!/:na]
        at org.eclipse.dirigible.components.jobs.config.CustomConnectionProvider.getConnection(CustomConnectionProvider.java:44) ~[dirigible-components-engine-jobs-11.0.0-SNAPSHOT.jar!/:na]
        at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:780) ~[quartz-2.3.2.jar!/:na]
        ... 4 common frames omitted
2024-03-29 09:42:15.667 [ERROR] [EclipseDirigibleScheduler_QuartzSchedulerThread] [background] org.quartz.core.ErrorLogger - An error occurred while org.quartz.impl.jdbcjobstore.JobStoreSupport$43@2d6cbb31
org.quartz.JobPersistenceException: Failed to obtain DB connection from data source 'SystemDB': java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30004ms.
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:783) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3854) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.retryExecuteInNonManagedTXLock(JobStoreSupport.java:3819) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.releaseAcquiredTrigger(JobStoreSupport.java:2940) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:363) ~[quartz-2.3.2.jar!/:na]
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30004ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[HikariCP-5.0.1.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181) ~[HikariCP-5.0.1.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[HikariCP-5.0.1.jar!/:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-5.0.1.jar!/:na]
        at org.eclipse.dirigible.components.jobs.config.CustomConnectionProvider.getConnection(CustomConnectionProvider.java:44) ~[dirigible-components-engine-jobs-11.0.0-SNAPSHOT.jar!/:na]
        at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:780) ~[quartz-2.3.2.jar!/:na]
        ... 5 common frames omitted
^C[42745.773s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 16k, detached.
[42745.773s][warning][os,thread] Failed to start the native thread for java.lang.Thread "SIGINT handler"
OpenJDK 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal SIGINT to handler- the VM may need to be forcibly terminated
^C[42746.216s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 16k, detached.
[42746.217s][warning][os,thread] Failed to start the native thread for java.lang.Thread "SIGINT handler"
OpenJDK 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal SIGINT to handler- the VM may need to be forcibly terminated
^C[42746.562s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 16k, detached.
[42746.562s][warning][os,thread] Failed to start the native thread for java.lang.Thread "SIGINT handler"
OpenJDK 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal SIGINT to handler- the VM may need to be forcibly terminated
^C[42746.804s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 16k, detached.
[42746.804s][warning][os,thread] Failed to start the native thread for java.lang.Thread "SIGINT handler"
OpenJDK 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal SIGINT to handler- the VM may need to be forcibly terminated
^C[42747.121s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 16k, detached.
[42747.121s][warning][os,thread] Failed to start the native thread for java.lang.Thread "SIGINT handler"
OpenJDK 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal SIGINT to handler- the VM may need to be forcibly terminated
```

**Comment by delchev** [comment]
Actually it was due to Timer Threads leak
