### ISSUE TITLE
[Che Integration] Configurable Temp Directory for Git

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#373]
Caused by: java.io.IOException: Permission denied
--
  | at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:1.8.0_181]
  | at java.io.File.createTempFile(File.java:2024) ~[na:1.8.0_181]
  | at java.io.File.createTempFile(File.java:2070) ~[na:1.8.0_181]
  | at org.eclipse.dirigible.core.git.utils.RepositoryFileUtils.createTempDirectory(RepositoryFileUtils.java:56) ~[dirigible-core-git-3.2.9-SNAPSHOT.jar:na]

**Comment by delchev** [comment]
Caused by: java.io.IOException: Permission denied
--
  | at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:1.8.0_181]
  | at java.io.File.createTempFile(File.java:2024) ~[na:1.8.0_181]
  | at java.io.File.createTempFile(File.java:2070) ~[na:1.8.0_181]
  | at org.eclipse.dirigible.core.git.utils.RepositoryFileUtils.createTempDirectory(RepositoryFileUtils.java:56) ~[dirigible-core-git-3.2.9-SNAPSHOT.jar:na]
  | at org.eclipse.dirigible.core.git.utils.RepositoryFileUtils.createTempDirectory(RepositoryFileUtils.java:41) ~[dirigible-core-git-3.2.9-SNAPSHOT.jar:na]
  | at org.eclipse.dirigible.core.git.utils.GitFileUtils.createTempDirectory(GitFileUtils.java:104) ~[dirigible-core-git-3.2.9-SNAPSHOT.jar:na]
  | at org.eclipse.dirigible.core.git.command.CloneCommand.createGitDirectory(CloneCommand.java:120) ~[dirigible-core-git-3.2.9-SNAPSHOT.jar:na]
  | at org.eclipse.dirigible.core.git.command.CloneCommand.execute(CloneCommand.java:94) ~[dirigible-core-git-3.2.9-SNAPSHOT.jar:na]
  | ... 52 common frames omitted
