### ISSUE TITLE
[EDM] NPE when creating schema with Report entity

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3740]
Even If I manually fix the generated schema JSON which is described [here](https://github.com/eclipse/dirigible/issues/3739), the schema cannot be created due to
```
2024-04-05 14:53:39.219 [ERROR] [pool-2-thread-1] [background] o.e.d.c.i.s.SynchronizationProcessor - Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at org.eclipse.dirigible.components.data.structures.synchronizer.SchemasSynchronizer.parseSchema(SchemasSynchronizer.java:239) ~[dirigible-components-data-structures-11.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.components.data.structures.synchronizer.SchemasSynchronizer.parse(SchemasSynchronizer.java:130) ~[dirigible-components-data-structures-11.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.components.initializers.synchronizer.SynchronizationProcessor.parseDefinitions(SynchronizationProcessor.java:492) ~[dirigible-components-core-initializers-11.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.components.initializers.synchronizer.SynchronizationProcessor.processSynchronizers(SynchronizationProcessor.java:192) ~[dirigible-components-core-initializers-11.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.components.initializers.synchronizer.SynchronizationJobService.executeSynchronizationJob(SynchronizationJobService.java:53) ~[dirigible-components-core-initializers-11.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.components.initializers.synchronizer.SynchronizationJob.lambda$execute$0(SynchronizationJob.java:117) ~[dirigible-components-core-initializers-11.0.0-SNAPSHOT.jar!/:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
2024-04-05 14:53:39.252 [ERROR] [pool-2-thread-1] [background] o.e.d.c.i.s.SynchronizationProcessor - Error occured during synchronization: [Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null]
```
Exception line [here](https://github.com/eclipse/dirigible/blob/1546fadbd3bcfa881764d5316692944eb4331bbb/components/data/data-structures/src/main/java/org/eclipse/dirigible/components/data/structures/synchronizer/SchemasSynchronizer.java#L239)
It looks like `referencedTable` is null but this is not expected.

**Comment by ThuF** [comment]
It seems that there were some issues with the model as commented here: https://github.com/eclipse/dirigible/issues/3739#issuecomment-2072776403
Once fixed, the generation should be executed successfully without exceptions.
