### ISSUE TITLE
When there is a leaked DB connections, the connection pool is exhausted 

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#4029]
When there is a leaked DB connections, the connection pool is exhausted and you are not able to obtain a new DB connection.
The only solution is to restart the application.

```
java.sql.SQLTransientConnectionException: HANA - Connection is not available, request timed out after 30003ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[HikariCP-5.0.1.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181) ~[HikariCP-5.0.1.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[HikariCP-5.0.1.jar!/:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-5.0.1.jar!/:na]
	at org.eclipse.dirigible.components.data.sources.manager.ManagedDataSource.getConnection(ManagedDataSource.java:62) ~[dirigible-components-data-sources-11.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.components.api.db.DatabaseFacade.getConnection(DatabaseFacade.java:542) ~[dirigible-components-api-database-11.0.0-SNAPSHOT.jar!/:na]
	at org.eclipse.dirigible.components.api.db.DatabaseFacade.getConnection(DatabaseFacade.java:525) ~[dirigible-components-api-database-11.0.0-SNAPSHOT.jar!/:na]
	at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeHandle(HostMethodDesc.java:371) ~[truffle-api-24.0.1.jar!/:na]
	at com.oracle.truffle.host.GuestToHostCodeCache$GuestToHostInvokeHandle.executeImpl(GuestToHostCodeCache.java:88) ~[truffle-api-24.0.1.jar!/:na]
	at com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:80) ~[truffle-api-24.0.1.jar!/:na]
```

**Comment by iliyan-velichkov** [comment]
fix: https://github.com/eclipse/dirigible/pull/4030
