### ISSUE TITLE
[Core] Messaging Handler - Context has not been initialized

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#418]
```java
org.mozilla.javascript.WrappedException: Wrapped org.eclipse.dirigible.commons.api.context.ContextException: Context has not been initialized (core/v3/java.js#15)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.gen.core_v3_java_js_1650._c_anonymous_1(core/v3/java.js:15) ~[na:na]
	at org.mozilla.javascript.gen.core_v3_java_js_1650.call(core/v3/java.js) ~[na:na]
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.gen.db_v3_database_js_1658._c_anonymous_5(db/v3/database.js:43) ~[na:na]
	at org.mozilla.javascript.gen.db_v3_database_js_1658.call(db/v3/database.js) ~[na:na]
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.gen.db_v3_dao_js_1652._c_anonymous_1(db/v3/dao.js:31) ~[na:na]
	at org.mozilla.javascript.gen.db_v3_dao_js_1652.call(db/v3/dao.js) ~[na:na]
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:359) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2655) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.gen.db_v3_dao_js_1652._c_anonymous_31(db/v3/dao.js:871) ~[na:na]
	at org.mozilla.javascript.gen.db_v3_dao_js_1652.call(db/v3/dao.js) ~[na:na]
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.gen.zeus_build_data_dao_Deliver_Secrets_js_1648._c_script_0(zeus-build/data/dao/Deliver/Secrets.js:4) ~[na:na]
	at org.mozilla.javascript.gen.zeus_build_data_dao_Deliver_Secrets_js_1648.call(zeus-build/data/dao/Deliver/Secrets.js) ~[na:na]
	at org.mozilla.javascript.gen.zeus_build_data_dao_Deliver_Secrets_js_1648.exec(zeus-build/data/dao/Deliver/Secrets.js) ~[na:na]
	at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:342) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:290) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.commonjs.module.Require.call(Require.java:219) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.gen.zeus_build_process_handler_js_1646._c_anonymous_1(zeus-build-process/handler.js:4) ~[na:na]
	at org.mozilla.javascript.gen.zeus_build_process_handler_js_1646.call(zeus-build-process/handler.js) ~[na:na]
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.gen.messaging_wrappers_onMessage_1644._c_script_0(messaging/wrappers/onMessage:11) ~[na:na]
	at org.mozilla.javascript.gen.messaging_wrappers_onMessage_1644.call(messaging/wrappers/onMessage) ~[na:na]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508) ~[rhino-1.7.10.jar:1.7.10]
	at org.mozilla.javascript.gen.messaging_wrappers_onMessage_1644.call(messaging/wrappers/onMessage) ~[na:na]
	at org.mozilla.javascript.gen.messaging_wrappers_onMessage_1644.exec(messaging/wrappers/onMessage) ~[na:na]
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1293) ~[rhino-1.7.10.jar:1.7.10]
	at org.eclipse.dirigible.engine.js.rhino.processor.RhinoJavascriptEngineExecutor.executeService(RhinoJavascriptEngineExecutor.java:167) ~[dirigible-engine-javascript-rhino-3.3.2-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.engine.js.rhino.processor.RhinoJavascriptEngineExecutor.executeServiceModule(RhinoJavascriptEngineExecutor.java:90) ~[dirigible-engine-javascript-rhino-3.3.2-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.engine.js.processor.DefaultJavascriptEngineExecutor.executeServiceModule(DefaultJavascriptEngineExecutor.java:60) ~[dirigible-engine-javascript-3.3.2-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.engine.api.script.ScriptEngineExecutorsManager.executeServiceModule(ScriptEngineExecutorsManager.java:40) ~[dirigible-engine-api-3.3.2-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.messaging.service.MessagingConsumer.receiveMessage(MessagingConsumer.java:143) [dirigible-core-messaging-3.3.2-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.messaging.service.MessagingConsumer.run(MessagingConsumer.java:100) [dirigible-core-messaging-3.3.2-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: org.eclipse.dirigible.commons.api.context.ContextException: Context has not been initialized
	at org.eclipse.dirigible.commons.api.context.ThreadContextFacade.checkContext(ThreadContextFacade.java:129) ~[dirigible-commons-api-3.3.2-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.commons.api.context.ThreadContextFacade.setProxy(ThreadContextFacade.java:193) ~[dirigible-commons-api-3.3.2-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.commons.api.context.ThreadContextFacade.setProxy(ThreadContextFacade.java:167) ~[dirigible-commons-api-3.3.2-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.api.v3.core.JavaFacade.call(JavaFacade.java:108) ~[dirigible-api-facade-core-3.3.2-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) ~[rhino-1.7.10.jar:1.7.10]
	... 39 common frames omitted

```

**Comment by ThuF** [comment]
Workaround - in this example **_db/v4/database_** API can be used instead of  **_db/v3/database_** API.
