### ISSUE TITLE
Dirigible 3.5 SAP All release doesn't start on SCP

### ISSUE THREAD

**Issue by Scorze** [eclipse/dirigible#450]
The newest version 3.5 dirigible SAP All release doesn't start on the SAP Cloud Platform. I get the following exception : 
```
019 09 11 09:32:31#+0300#ERROR#org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/]##anonymous#localhost-startStop-1#na#u925t4tjtk#dirigible3test#web##na#na#na#na#Exception sending context initialized event to listener instance of class [org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener] com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to org.eclipse.dirigible.repository.api.IRepository was already configured at org.eclipse.dirigible.repository.local.module.LocalRepositoryModule.configure(LocalRepositoryModule.java:41) (via modules: org.eclipse.dirigible.commons.api.module.DirigibleModulesInstallerModule -> org.eclipse.dirigible.repository.local.module.LocalRepositoryModule).
at org.eclipse.dirigible.repository.db.module.DatabaseRepositoryModule.configure(DatabaseRepositoryModule.java:50) (via modules: org.eclipse.dirigible.commons.api.module.DirigibleModulesInstallerModule -> org.eclipse.dirigible.repository.db.module.DatabaseRepositoryModule)

1 error
at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
at com.google.inject.Guice.createInjector(Guice.java:87)
at com.google.inject.Guice.createInjector(Guice.java:69)
at com.google.inject.Guice.createInjector(Guice.java:59)
at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.getInjector(DirigibleInitializer.java:60)
at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.getInjector(DirigibleServletContextListener.java:40)
at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:49)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4792)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:836)
```

**Comment by delchev** [comment]
Fixed with:
3.5.1 -> https://github.com/eclipse/dirigible/commit/cf569db707ce8028b2388385732301c6b6e68da4
4.0.0 -> https://github.com/eclipse/dirigible/commit/3b6a2d33f22ea1b948747231ea52df5725d544c3
