### ISSUE TITLE
[Releng] SAP Build - CMS - unable to start

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#552]
**Describe the bug**
Unable to start "SAP CMS" build on SAP Cloud Platform (Neo)

**Exception - Unable to create injector**
```java
Exception sending context initialized event to listener instance of class [org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener] com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to org.eclipse.dirigible.repository.api.IRepository was already configured at org.eclipse.dirigible.repository.db.module.DatabaseRepositoryModule.configure(DatabaseRepositoryModule.java:50) (via modules: org.eclipse.dirigible.commons.api.module.DirigibleModulesInstallerModule -> org.eclipse.dirigible.repository.db.module.DatabaseRepositoryModule).
  at org.eclipse.dirigible.repository.local.module.LocalRepositoryModule.configure(LocalRepositoryModule.java:41) (via modules: org.eclipse.dirigible.commons.api.module.DirigibleModulesInstallerModule -> org.eclipse.dirigible.repository.local.module.LocalRepositoryModule)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.getInjector(DirigibleInitializer.java:60)
	at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.getInjector(DirigibleServletContextListener.java:40)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:49)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4701)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:836)
```

**Comment by ThuF** [comment]
Related to:
- https://github.com/eclipse/dirigible/issues/484
- https://github.com/eclipse/dirigible/issues/452
