### ISSUE TITLE
[IDE] Git Perspective Issue (Committed Code is not present in github)

### ISSUE THREAD

**Issue by ujval-kalal** [eclipse/dirigible#645]
**Describe the bug**
I pushed file to the git remote repo from dirigible git perspective but the committed transaction is not logged in git hub. later did blank push with comments then we can see the both the commit transactions in git remote repo.

**To Reproduce**
1. Go to 'Dirigible Git Perspective'
2. Click on 'select files and add comment and then click commit & Push'
3. Go to 'GitHub Remote repo'
4.scroll and check 'Does Committed files are present in repo' 
4. See error ''

**Expected behavior**
committed file should be visible in git remote repo

**Desktop :**
 - OS: widows 10 pro
 - Browser google Chrome
 - Version 

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/72190161/99031879-26be5380-259e-11eb-9790-b7455dc2b088.png)
![gitpusherror](https://user-images.githubusercontent.com/72190161/99031922-3c337d80-259e-11eb-9579-380674eebd2b.jpg)

**Comment by ThuF** [comment]
Potentially related exception: `java.net.UnknownHostException: github.com`

Stacktrace:
```java
org.eclipse.jgit.api.errors.TransportException: https://github.com/dirigiblelabs/ide-workspace.git: cannot open git-receive-pack
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:180) ~[org.eclipse.jgit-5.5.0.201909110433-r.jar:5.5.0.201909110433-r]
	at org.eclipse.dirigible.core.git.GitConnector.push(GitConnector.java:259) ~[dirigible-core-git-5.8.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.git.command.PushCommand.pushProjectToGitRepository(PushCommand.java:143) ~[dirigible-core-git-5.8.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.git.command.PushCommand.execute(PushCommand.java:87) ~[dirigible-core-git-5.8.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.runtime.git.processor.GitProcessor.push(GitProcessor.java:133) ~[dirigible-ide-service-git-5.8.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.runtime.git.service.GitRestService.pushProject(GitRestService.java:192) ~[dirigible-ide-service-git-5.8.0-SNAPSHOT.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[cxf-rt-frontend-jaxrs-3.4.2.jar:3.4.2]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[cxf-rt-frontend-jaxrs-3.4.2.jar:3.4.2]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[servlet-api.jar:na]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.eclipse.dirigible.runtime.core.filter.HealthCheckFilter.doFilter(HealthCheckFilter.java:50) ~[dirigible-service-core-5.8.0-SNAPSHOT.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.eclipse.dirigible.runtime.core.filter.HttpContextFilter.doFilter(HttpContextFilter.java:57) ~[dirigible-service-core-5.8.0-SNAPSHOT.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364) ~[catalina.jar:8.5.43]
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:482) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:327) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:297) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.eclipse.jetty.servlets.QoSFilter.doFilter(QoSFilter.java:203) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at com.google.inject.servlet.DefaultFilterPipeline.dispatch(DefaultFilterPipeline.java:47) ~[guice-servlet-4.2.2.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133) ~[guice-servlet-4.2.2.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.43]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) ~[catalina.jar:8.5.43]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.43]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.43]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:8.5.43]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.43]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.43]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/dirigiblelabs/ide-workspace.git: cannot open git-receive-pack
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:626) ~[org.eclipse.jgit-5.5.0.201909110433-r.jar:5.5.0.201909110433-r]
	at org.eclipse.jgit.transport.TransportHttp.openPush(TransportHttp.java:467) ~[org.eclipse.jgit-5.5.0.201909110433-r.jar:5.5.0.201909110433-r]
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:160) ~[org.eclipse.jgit-5.5.0.201909110433-r.jar:5.5.0.201909110433-r]
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1367) ~[org.eclipse.jgit-5.5.0.201909110433-r.jar:5.5.0.201909110433-r]
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:170) ~[org.eclipse.jgit-5.5.0.201909110433-r.jar:5.5.0.201909110433-r]
	... 70 common frames omitted
Caused by: java.net.UnknownHostException: github.com
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) ~[na:na]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1227) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[na:na]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515) ~[na:na]
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[na:na]
	at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:115) ~[org.eclipse.jgit-5.5.0.201909110433-r.jar:5.5.0.201909110433-r]
	at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:228) ~[org.eclipse.jgit-5.5.0.201909110433-r.jar:5.5.0.201909110433-r]
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:540) ~[org.eclipse.jgit-5.5.0.201909110433-r.jar:5.5.0.201909110433-r]
	... 74 common frames omitted

```

**Comment by ThuF** [comment]
Better exception handling and user feedback to be introduced.

Can be workarounded by the following steps:
1. Select the git repository from the file explorer _(Git Perspective)_.
2. Right click on it.
3. Select the `Push` option
4. Enter the required credentials
5. Push to the remote repository

**Comment by ThuF** [comment]
To be tracked as part of the general improvement of the IDE notifications:
- https://github.com/eclipse/dirigible/issues/786
