### ISSUE TITLE
[IDE] Documents - Security Access Utils Error

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#646]
```java
Caused by: org.graalvm.polyglot.PolyglotException: Error: Error executing module ide-documents/security/accessUtils line #undefined : Error executing module ide-documents/api/lib/document line #undefined : Error executing module ide-documents/api/lib/object line #undefined : undefined
	at <js>._require(Unnamed:1) ~[na:na]
	at <js>.:anonymous(Unnamed:1) ~[na:na]
	at <js>.:program(Unnamed:11) ~[na:na]
	at org.graalvm.polyglot.Context.eval(Context.java:371) ~[graal-sdk-20.0.0.jar:na]
	at org.eclipse.dirigible.engine.js.graalvm.processor.GraalVMJavascriptEngineExecutor.executeService(GraalVMJavascriptEngineExecutor.java:129) ~[dirigible-engine-javascript-graalvm-5.5.0.jar:na]
	at org.eclipse.dirigible.engine.js.graalvm.processor.GraalVMJavascriptEngineExecutor.executeServiceModule(GraalVMJavascriptEngineExecutor.java:63) ~[dirigible-engine-javascript-graalvm-5.5.0.jar:na]
	at org.eclipse.dirigible.engine.js.processor.DefaultJavascriptEngineExecutor.executeServiceModule(DefaultJavascriptEngineExecutor.java:57) ~[dirigible-engine-javascript-5.5.0.jar:na]
	at org.eclipse.dirigible.engine.api.script.ScriptEngineExecutorsManager.executeServiceModule(ScriptEngineExecutorsManager.java:42) ~[dirigible-engine-api-5.5.0.jar:na]
	at org.eclipse.dirigible.core.scheduler.handler.JobHandler.execute(JobHandler.java:33) ~[dirigible-core-scheduler-5.5.0.jar:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:na]
	... 1 common frames omitted
```

**Comment by delchev** [comment]
It's due to a wrong dependencies and configuration, for instance if it is used:

> dirigible-cms-database

also the following environment variables have to be set:

   export DIRIGIBLE_CMS_PROVIDER=database
   export DIRIGIBLE_CMS_DATABASE_DATASOURCE_TYPE=custom
   export DIRIGIBLE_CMS_DATABASE_DATASOURCE_NAME=<name of the datasource>

more info:
https://www.dirigible.io/help/setup/setup-environment-variables/#cms-database
