### ISSUE TITLE
[Releng] SAP CF Runtime only deployment is not working

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#652]
It seems that there is an issue with the SAP CF Runtime only deployment. Further investigation is needed.

**Comment by ThuF** [comment]
It seems that the reason for this issue is a misconfiguration - missing XSUAA service binding:

```java
org.eclipse.dirigible.commons.api.context.InvalidStateException: No XSUAA service instance is bound
```

Stactrace:
```java
com.google.inject.internal.MessageProcessor.visit An exception was caught and reported. Message: org.eclipse.dirigible.commons.api.context.InvalidStateException: No XSUAA service instance is bound
org.eclipse.dirigible.commons.api.context.InvalidStateException: No XSUAA service instance is bound
    at org.eclipse.dirigible.cf.CloudFoundryModule.configureOAuth(CloudFoundryModule.java:73)
    at org.eclipse.dirigible.cf.CloudFoundryModule.configure(CloudFoundryModule.java:60)
    at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
    at com.google.inject.AbstractModule.install(AbstractModule.java:103)
    at org.eclipse.dirigible.commons.api.module.DirigibleModulesInstallerModule.configure(DirigibleModulesInstallerModule.java:60)
    at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
    at com.google.inject.spi.Elements.getElements(Elements.java:103)
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
    at com.google.inject.Guice.createInjector(Guice.java:87)
    at com.google.inject.Guice.createInjector(Guice.java:69)
    at com.google.inject.Guice.createInjector(Guice.java:59)
    at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.getInjector(DirigibleInitializer.java:61)
    at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.getInjector(DirigibleServletContextListener.java:41)
    at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
    at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:50)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1859)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

Once the service instance binding is configured, the application runs as expected.
