### ISSUE TITLE
Fails to initialize terminal server in windows environment

### ISSUE THREAD

**Issue by GrozevJunior** [eclipse/dirigible#748]
java.lang.ExceptionInInitializerError
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:315)
		at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.startupTerminalServer(DirigibleInitializer.java:245)
		at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initialize(DirigibleInitializer.java:86)
		at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:51)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: java.lang.IllegalStateException: Windows is not yet supported
		at org.eclipse.dirigible.runtime.ide.terminal.service.XTerminalWebsocketService.runTTYD(XTerminalWebsocketService.java:99)
		at org.eclipse.dirigible.runtime.ide.terminal.service.XTerminalWebsocketService.<clinit>(XTerminalWebsocketService.java:60)
		... 18 more

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/pull/750
