### ISSUE TITLE
[API] Console - Trace method is not showing the trace stack

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#906]
Sample code:

```javascript
console.trace("Trace Message");
```

Expected output:

```javascript
Trace: Trace Message
    at repl:1:9
    at Script.runInThisContext (vm.js:116:20)
    at REPLServer.defaultEval (repl.js:405:29)
    at bound (domain.js:419:14)
    at REPLServer.runBound [as eval] (domain.js:432:12)
    at REPLServer.onLine (repl.js:716:10)
    at REPLServer.emit (events.js:228:7)
    at REPLServer.EventEmitter.emit (domain.js:475:20)
    at REPLServer.Interface._onLine (readline.js:315:10)
    at REPLServer.Interface._line (readline.js:692:8)
```

**Comment by ThuF** [comment]
Sample solution:

```javascript
function trace(errorMessage) {
  try {
    throw new Error(errorMessage);
  } catch(e) {
    console.log(e.stack);
  }
}

trace("My Trace Message");
```
